#ifndef POWER_H
#define POWER_H

#define TEXTURE_BATTERY_0 35
#define TEXTURE_BATTERY_15 36
#define TEXTURE_BATTERY_28 37
#define TEXTURE_BATTERY_43 38
#define TEXTURE_BATTERY_57 39
#define TEXTURE_BATTERY_71 40
#define TEXTURE_BATTERY_85 41
#define TEXTURE_BATTERY_100 42
#define TEXTURE_BATTERY_CHARGE 43

void drawBatteryStatus(void);

#endif